In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\harsh\\Downloads\\analysis_id (1).csv")

In [3]:
df.columns

Index(['Unnamed: 0', 'date_hour', 'client', 'device_type', 'time_zone',
       'os_name', 'browser_name', 'ad_unit', 'size', 'bidder', 'bid_range',
       'media_type', 'request_count', 'response_count', 'prebid_win_count',
       'win_count', 'sum_bid', 'sum_time_to_respond', 'median', 'min_bid',
       'max_bid', 'avg_bid', 'sum_2nd_highest_bid', 'sum_prebid_winning_bid',
       'sum_winning_bid', 'sum_nobid', 'sum_timeout'],
      dtype='object')

In [4]:
df.shape

(5000, 27)

In [5]:
for col in df.columns:
    print(df[col].value_counts())
    print("\n\n")

Unnamed: 0
0       1
1       1
2       1
3       1
4       1
       ..
4995    1
4996    1
4997    1
4998    1
4999    1
Name: count, Length: 5000, dtype: int64



date_hour
2021-04-11T01:00:00    5000
Name: count, dtype: int64



client
asc126828    5000
Name: count, dtype: int64



device_type
Desktop    5000
Name: count, dtype: int64



time_zone
America/New_York        1739
America/Chicago         1094
America/Los_Angeles      730
America/Denver           488
America/Halifax          175
America/Phoenix          173
America/Indianapolis     171
UTC                       72
America/St_Johns          59
America/Detroit           58
Etc/GMT+5                 49
Europe/Moscow             39
Australia/Adelaide        32
Pacific/Honolulu          31
PST8PDT                   27
America/Toronto           22
Australia/Sydney          15
Europe/London              7
America/Vancouver          7
Europe/Stockholm           7
Asia/Jerusalem             5
Name: count, dtype: int64



os_name
Windows      3334
Macintosh    1058
Linux         608
Name: count, dtype: int64



browser_name
Chrome-89.04389114    2741
Chrome-89.043899       596
Chrome-86.04240198     223
Safari-14.03           201
Chrome-88.04324208     114
Chrome-61.0316379      112
Firefox-78             105
Chrome-83.04103106     103
Firefox-87             101
Chrome-88.04324192      86
Chrome-84.04147127      84
Chrome-89.04389116      61
Chrome-85.04183133      58
Chrome-87.04280142      50
Chrome-89.0438982       48
Safari-14.02            34
Chrome-84.04147136      28
Chrome-89.0438995       26
Chrome-88.0432419       24
Chrome-70.03538102      20
Chrome-59.0307186       16
Chrome-87.04280141      12
Mozilla-5               12
Firefox-86              12
Chrome-71.0357898       10
BlackBerry-1.1           9
Chrome-88.0432415        9
Chrome-91.04463          9
Chrome-92.04473          9
Chrome-88.04324182       8
Chrome-89.04389112       8
Safari-13.12             7
Firefox-85               7
Chrome-89.0438972        7
Chrome-87.0428088        6
Firefox-64               6
Chrome-53.02785143       6
Chrome-66.03359139       5
Safari-8.02              5
Chrome-79.0394513        5
Chrome-86.04240199       4
Chrome-81.04044268       4
Chrome-51.0270463        3
Safari-12.12             2
Safari-13.11             2
Chrome-89.04389122       1
Chrome-49.02623112       1
Name: count, dtype: int64



ad_unit
div-gpt-ad-BT-D-SideBar-T        532
div-gpt-ad-BT-D-Footers          396
div-gpt-ad-BT-D-SideBar-1        303
div-gpt-ad-BT-D-Sidebar-B        259
div-gpt-ad-BT-D-InLine-1         259
                                ...
div-gpt-ad-BT-T-InPost-3_1_11      1
div-gpt-ad-BT-T-InPost-9_1_45      1
div-gpt-ad-BT-T-InPost-9_1_51      1
div-gpt-ad-BT-D-InPost-8_1_96      1
div-gpt-ad-BT-D-InPost-1_1_17      1
Name: count, Length: 260, dtype: int64



size
300x250    2277
728x90     1323
468x60      351
336x280     346
300x600     180
160x600     163
310x260     151
970x90      111
1x1          92
320x50        4
320x100       2
Name: count, dtype: int64



bidder
                1210
ix               464
onemobile        407
medianet         384
criteo           306
pubmatic         298
rhythmone        246
33across         240
triplelift       232
openx            197
appnexus         197
rubicon          178
emx_digital      169
sharethrough     139
pulsepoint       134
sovrn            102
undertone         49
teads             48
Name: count, dtype: int64



bid_range
           1210
0-0.1       628
0.1-0.2     604
0.2-0.3     540
0.3-0.4     327
           ...
5.8-5.9       1
3.8-3.9       1
5.7-5.8       1
8.8-8.9       1
6-6.1         1
Name: count, Length: 66, dtype: int64



media_type
display    5000
Name: count, dtype: int64



request_count
1       2239
2        480
3        255
20       243
19       233
        ...
8941       1
732        1
544        1
2445       1
125        1
Name: count, Length: 258, dtype: int64



response_count
1      2239
0      1210
2       480
3       255
4       142
       ...
88        1
163       1
183       1
83        1
125       1
Name: count, Length: 112, dtype: int64



prebid_win_count
1.0      761
2.0      165
3.0       47
4.0       33
6.0       32
5.0       31
7.0       14
8.0       11
9.0       10
12.0      10
10.0       9
13.0       5
14.0       5
15.0       3
16.0       3
25.0       2
28.0       2
21.0       2
20.0       2
19.0       2
18.0       2
23.0       2
17.0       2
100.0      1
30.0       1
27.0       1
33.0       1
35.0       1
37.0       1
70.0       1
144.0      1
44.0       1
22.0       1
11.0       1
36.0       1
Name: count, dtype: int64



win_count
1.0     150
2.0      20
3.0       5
4.0       5
6.0       2
13.0      1
5.0       1
16.0      1
7.0       1
Name: count, dtype: int64



sum_bid
0.038000     41
0.028500     21
0.076000     21
0.019000     21
0.279000     19
             ..
4.073836      1
14.894300     1
0.624160      1
14.571880     1
0.107800      1
Name: count, Length: 2770, dtype: int64



sum_time_to_respond
482.0     8
308.0     8
247.0     7
320.0     7
330.0     7
         ..
6629.0    1
1106.0    1
1896.0    1
2064.0    1
4823.0    1
Name: count, Length: 2328, dtype: int64



median
0.038000    23
0.279000    16
0.019000    14
0.028500    12
0.047000    10
            ..
1.426900     1
1.903245     1
1.685600     1
0.151708     1
1.039182     1
Name: count, Length: 1253, dtype: int64



min_bid
0.009500    50
0.279000    50
0.038000    48
0.184000    31
0.019000    29
            ..
0.133456     1
0.333052     1
0.392274     1
0.123410     1
0.079478     1
Name: count, Length: 2184, dtype: int64



max_bid
0.038000    45
0.279000    33
0.076000    31
0.184000    27
0.095000    27
            ..
0.192808     1
1.685600     1
1.903245     1
1.426900     1
0.485000     1
Name: count, Length: 2277, dtype: int64



avg_bid
0.038000    42
0.279000    33
0.184000    27
0.028500    24
0.019000    22
            ..
1.028475     1
0.245520     1
7.447150     1
0.624160     1
0.890493     1
Name: count, Length: 2705, dtype: int64



sum_2nd_highest_bid
0.038000    9
0.028500    6
0.095000    5
0.009500    5
0.066500    5
           ..
0.635440    1
0.716990    1
1.164000    1
1.076076    1
1.215464    1
Name: count, Length: 603, dtype: int64



sum_prebid_winning_bid
0.279000    10
2.880000     7
0.028500     7
0.095000     7
0.558000     6
            ..
3.209616     1
1.337250     1
2.062723     1
0.199083     1
3.449887     1
Name: count, Length: 994, dtype: int64



sum_winning_bid
0.960000    5
1.104000    3
0.686070    3
0.075200    2
2.880000    2
           ..
0.494000    1
0.203980    1
1.743750    1
0.799000    1
2.205565    1
Name: count, Length: 171, dtype: int64



Series([], Name: count, dtype: int64)



Series([], Name: count, dtype: int64)

In [6]:
df.isna().sum()

Unnamed: 0                   0
date_hour                    0
client                       0
device_type                  0
time_zone                    0
os_name                      0
browser_name                 0
ad_unit                      0
size                         0
bidder                       0
bid_range                    0
media_type                   0
request_count                0
response_count               0
prebid_win_count          3833
win_count                 4814
sum_bid                   1210
sum_time_to_respond       1210
median                    3240
min_bid                   1210
max_bid                   1210
avg_bid                   1210
sum_2nd_highest_bid       4266
sum_prebid_winning_bid    3833
sum_winning_bid           4814
sum_nobid                 5000
sum_timeout               5000
dtype: int64

In [7]:
df.head(5)

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
0,0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,...,6614.0,NaN,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN
1,1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,...,5171.0,NaN,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN
2,2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,...,1523.0,NaN,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN
3,3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,...,3570.0,0.34875,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN

In [8]:
df_agg = df.groupby("bidder").agg({"prebid_win_count": "sum", "request_count": "sum"}).reset_index()

In [9]:
df_agg["win_rate"] = df_agg['prebid_win_count'] / df_agg['request_count']

In [10]:
top2_win_rate = df_agg.sort_values("win_rate", ascending=False).head(2)
top2_win_rate

       bidder  prebid_win_count  request_count  win_rate
17  undertone              52.0            104  0.500000
15      teads             323.0            700  0.461429